jobs:
  build:
    docker:
      - image: circleci/php:7.2-stretch-node
    environment:
      - THEME_PATH: "vendor/snowdog/module-alpaca-components"
      - CONFIG_PATH: "vendor/snowdog/module-alpaca-components/.circleci/frontools/config"
    steps:
      - checkout
      - run: mkdir -p $THEME_PATH
      - run: rsync -r --delete . $THEME_PATH
      - run: cp "$THEME_PATH/composer.json" .
      - run: composer require snowdog/frontools --no-interaction --prefer-dist
      - run: mkdir -p dev/tools/frontools
      - run: cp -r $CONFIG_PATH dev/tools/frontools
      - run: cd vendor/snowdog/frontools && yarn && yarn setup
      - run: cd tools && yarn inheritance
      - run: cd tools && yarn sasslint --ci
      - run: cd tools && yarn styles --ci --pipeline
      - run: cd tools && yarn csslint --ci
