module.exports = {
  title: 'Icons',
  status: 'wip',
  context: {
    icons: [
      'icon-arrow-down',
      'icon-arrow-right',
      'icon-arrow-up',
      'icon-carousel-left',
      'icon-carousel-right',
      'icon-close',
      'icon-fb',
      'icon-full-screen',
      'icon-google',
      'icon-heating',
      'icon-installation',
      'icon-linkedin',
      'icon-mobile-menu',
      'icon-heating-2',
      'icon-ok',
      'icon-plus',
      'icon-search',
      'icon-twitter',
      'icon-water',
      'icon-x',
      'loader',
      'icon-info-project',
      'icon-search-project',
      'icon-twitter-project',
      'icon-pinterest-project',
      'icon-houzz-project',
      'icon-instagram-project',
      'icon-facebook-project',
      'icon-like-project',
      'icon-cart-project',
      'icon-arrow-left-project',
      'icon-mail-project',
      'icon-edit-project',
      'icon-delete-project'
    ]
  }
};
